### ISSUE TITLE
Add custom log format.

### ISSUE THREAD

**Issue by Los-had** [Los-had/logpy#2]
the default log format is:
```
[(level)] (time) - (msg)
```

maybe add a paramater in the logger class initializer for customize the log format.

**Comment by Los-had** [comment]
already implemented

**Comment by Thedijje** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
anhnt, @akirawuc, @rolandtshen, @GQhighroller, @leoarmelin, @yana-o, @0xRory, @gbr5, @mkos11, @fakemonkgin, @biwow, @bryansayler, @kadenzipfel, @imuhammadshoaib, @foriacus, @hannah-eichelsdoerfer, @uleeeeee, @sustainjane98, @Sabnock01, @njwardhan, @Adidas8023, @heypran, @newt0, @Jds-23, @ninja-1337, @mastguer, @karnpapon, @radchukd, @mani3h, @Alexintosh, @orangeflame, @pengkobe, @SmallRuralDog, @mustafaskyer, @nikichv, @D-lyw, @Agilulfo1820, @bernd-k1337, @da-022412, @EES-Liuzhenye, @joselvelez, @anazach, @elaoshi, @linkdrone, @KABBOUCHI, @padi-dev-hoangpa, @slkass, @meta-bowen, @gggoaaat, @WKlilibenjioh5, @phpmac, @NightFeather0615, @kwoktung, @qiuchenghui, @au5ton, @Ph3nol, @zakimzf, @qdriven, @doplur, @King-fly, @Caruso33, @carllippert, @blackstorm, @phanvankhanh, @Alexey1100, @shavidzet, @SexySnowBunny69, @lingyong, @edakturk14, @oieduardorabelo, @hainusii, @ilyalesik, @r-strawser, @HipyCas, @amdev9, @chrismaree, @eyooooo, @otaldonuness, @waqaswahid1, @KevinVitale, @iamsantek, @DevArcane, @Cornelius-Mutisya, @transitive-bullshit, @pguardiario, @metaforcode, @vasinl124, @JiuBanA1, @hansongwang, @kevinjoshi46b, @miraclesu-to, @kesne, @TamtamHero, @bijeebuss, @ZXM0000, @alexanderdoty, @iMuzz, @irpic, @RogerHiguereyAdemKao, @philogicae, @NorthHub, @Ozone2037, @mul1sh, @JonahGlasgow, @mortemn, @MY-BNH, @vinhphamdev, @Charlesbutter1, @cbovis, @mchalise, @meiwhu, @merkle-groot, @0xJamesBong, @BossaNovaCC, @jimleuk, @aarondancer, @disestevez, @realm520, @Big-Aaron, @remyzv, @skundu42, @bvanderlugt, @bulutarda, @reslear, @evazhang612, @0xRian, @jingledongding, @Sabnock01, @alsoeoe, @WoeOm, @kadenzipfel, @ken0nek, @dingyi, @mnz12138, @abraham-yusuf, @fffedor, @joshstow, @hubery1996, @bububa, @xiaoxiaosaohuo, @andy00614, @sebastiantf, @TheOnlyBeardedBeast, @oka74d4, @hkbnkityeung, @andreystarkov, @basememara, @nazrdogan

**Comment by upccjesse** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
ebramanti, @rohan-201, @alchemistgo87, @austbot, @nitintf, @ripoff2, @IngeniousArtist, @wcnrny, @Razgatli1071, @andyluss, @2170cell, @TenviLi, @Razzer00, @rj8574, @b4s36t4, @charann29, @tribuste, @3m4r5, @vagxrth, @AlienCode4, @michaelborg05, @kunal021, @GalenDiogenes, @ALMaclaine, @zahin-mohammad, @Rashida318, @bricestacey, @shashank40, @Bhavika-14, @johnsonbhaskaran, @tuvudu, @96mohitm, @emmadeeofficial, @cherbert0123, @AmAzing129, @cubix1222, @result17, @dreamineering, @iamvon, @SnapRandom, @aryan7778, @cogoo, @qapquiz, @adarsh-technocrat, @sherrbss, @pavan-pv, @umarluqman, @Nguyenhoa1235, @izkizk8, @exromanysoummyaanon, @Giri-iconic, @adityaraj5200, @izkizk8, @Tripathiaman2511, @sreyas7, @Chandradeep-Pra, @ICLXL, @andnasnd, @ChinmayMhatre, @vrohlfs, @zouguangxian, @varshitverma, @davidp94, @ErnestChinedu, @IngeniousArtist, @thanhphuoc95, @EhretiaAcuminata, @zohadev, @Pulko, @BulentSE, @SnapRandom, @Shahi1i23, @skport, @yairyintrk, @kbulte, @Sarath343, @g-utsav, @agustif, @zahin-mohammad, @theDheerajjha, @skynetcap, @philiporange, @yamen, @ericjee, @dhruv160410116084, @souravghosh01, @tribuste, @code-sharad, @Anvesh100, @tcchawla, @tolgaand, @them2dt, @3m4r5, @gagliardetto, @statikdev, @hbk671104, @Hassanxj, @Bhavika-14, @lingxiyangsouravghosh01, @Shahi1i23, @jessb321, @OEGOD, @ReeRiley, @Pegasus321, @flawlesscode254, @sayantank, @dotamir, @quartesa37, @notmatical, @ajobi-uhc, @GauravKanwat, @UpRising00, @muhammetselimfe, @chrajeshdagur, @cogoo, @tuvudu, @wentokay, @csjcode, @oswaldb22, @MioQuispe, @SUMMERlove1, @ErnestChinedu, @Neelk131, @akeem, @ashokpeeta, @emmadeeofficial, @joemccann, @usyarif, @itsmeajay1699, @hydrogenbond007, @haomaaax, @h4rkl, @shockz09, @oooaaabaka, @alchemistgo87, @tuanductran, @MuhtasimTanmoy, @kootsZhin, @fluturecode, @michaelborg05, @kunaldo07, @qbig, @zhaijunyu, @idkDemo, @ritwikchakraborty123, @rektdegen, @yairyintrk, @gaylonalfano
